apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: order-api-prod
  namespace: argocd

spec:
  project: default

  sources:

    - repoURL: https://github.com/abdosaad203/helm-backend.git
      targetRevision: main
      path: backend

      helm:
        valueFiles:
          - values/order-gitops-prod.yaml
          - $values/environments/prod/order-api.yaml

    - repoURL: https://github.com/abdosaad203/ecommerce-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true