apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: catalog-api-monitor
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: catalog-api

  namespaceSelector:
    any: true

  endpoints:
    - port: http
      path: /metrics
      interval: 15s