apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: high-error-rate
  namespace: monitoring

spec:
  groups:
    - name: ecommerce-alerts

      rules:
        - alert: HighErrorRate

          expr: rate(http_requests_received_total{code=~"5.."}[1m]) > 0

          for: 1m

          labels:
            severity: critical

          annotations:
            summary: "High HTTP 5xx error rate detected"
            description: "Application is returning server errors."