apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring-stack
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.5.2

    helm:
      values: |
        grafana:
          enabled: true

          adminPassword: admin123

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 100m
              memory: 128Mi

        prometheus:
          enabled: true

          prometheusSpec:
            retention: 1d

            resources:
              requests:
                cpu: 100m
                memory: 128Mi

              limits:
                cpu: 200m
                memory: 256Mi

        alertmanager:
          enabled: false

        kube-state-metrics:
          enabled: true

        prometheus-node-exporter:
          enabled: true

        prometheusOperator:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 100m
              memory: 128Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true